config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get 'map', to: 'pages#map'
  resources :reports, only: %i[update]
  resources :spots do
    resources :reviews, only: %i[new create] do
      resources :likes, only: %i[create] do
        collection do
          delete :destroy
        end
      end
    end
  end
  resources :reviews, only: %i[destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots do
    resources :favorites, only: %i[create] do
      collection do
        delete :destroy
      end
    end
  end
  resources :spots, :reviews do
    resources :reports, only: %i[new create]
  end
  resources :reports, only: %i[destroy]
  get "outlaws/:id", to: "outlaws#banned", as: :outlaw
end

app/models/spot.rb
class Spot < ApplicationRecord
  CATEGORIES = %w[Monument Mirador Panoramic Beach Bay Cliff]
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :photos
  validates :category, inclusion: { in: CATEGORIES,
    message: "%{value} is not a valid category" }
  has_many :reviewed_spots, through: :reviews, source: :user, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :fetch_spot, only: %i[update show destroy]

  def index
    @spots = Spot.all.order(created_at: :desc)
    @user = current_user
    @categories = Spot::CATEGORIES

    # favorites
    if @user
      @favorites = @user.favorites
    end


    # search
    if params[:query].present?
      sql_query = " \
        spots.name @@ :query \
        OR spots.address @@ :query \
        OR spots.category @@ :query \
      "

      @spots = @spots.where(sql_query, query: "%#{params[:query]}%")
    end
    if params[:category].present?
      @spots = @spots.where(category: params[:category])
    end
    if @spots.empty?
      flash.now[:alert] = "Sorry, we could not find what you're looking for."
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @user = current_user
    @reviews = @spot.reviews
    @pictures = @spot.photos
    @spot.reviews.each do |r|
      if r.photos.attached?
        r.photos.each do |picture|
          @pictures << picture
        end
        @pictures
      end
    end


    if @user
      @favorites = @user.favorites
    end

    @report = @spot.reports.new

	end

  def new
    @spot = Spot.new
    @categories = Spot::CATEGORIES
  end

  def create
    @spot = Spot.new(spots_params)
    @spot.user = current_user
    if @spot.save
      redirect_to spot_path(@spot)
    else
      render "new"
    end
  end

   def edit
    @spot = Spot.find(params[:id])
  end

   def update
    # @spot.update(spots_params)
    # redirect_to spot_path(@spot)
    if @spot.user == current_user || current_user.moderator?
      @spot.update(spots_params)
      if current_user.moderator?
        redirect_to dashboard_path(anchor: :upcoming)
      else
      redirect_to spot_path(@spot)
      end
     else
      flash.now[:alert] = "Sorry, you dont have that permission."
      # redirect_to spot_path(@spot)
      redirect_back(fallback_location: root_path)
     end
  end

    def destroy
    # @spot = Spot.find(params[:id])
    if current_user
      if @spot.user == current_user || current_user.moderator?
      @spot.destroy
      redirect_to dashboard_path(anchor: :upcoming)
      # redirect_back(fallback_location: root_path)

      else
      flash.now[:alert] = "Sorry, you dont have that permission."
      # redirect_to dashboard_path
      redirect_back(fallback_location: root_path)

      end
    end
    end

	private

  def fetch_spot
    @spot = Spot.find(params[:id])
  end

  def spots_params
    params.require(:spot).permit(:name, :address, :description, :category, photos: [])
  end
end

app/helpers/spot_helper.rb
module SpotHelper
  def spot_image_tag(spot)
    if spot.photo.attached?
      cl_image_tag(spot.photo.key)
    else
      # cl_image_path('cocktail_placeholder')
      image_tag('spot.jpg')
    end
  end

  def avg_rating(spot)
    reviews = spot.reviews
    if reviews.any?
      sum = 0
      reviews.each do |r|
        sum += r.rating
      end
      sum / reviews.count
    else
      0
    end
  end
end

app/views/spots/_moderator_destroy.html.erb
<div class="actions">
  <%= link_to edit_spot_path(spot), class: 'actions_btn' do %>
  	<i class="fas fa-edit"></i>
  <%end%>
  <%= link_to spot_path(spot), class: 'actions_btn', method: :delete, data: {confirm: 'Do you want to delete the spot?'} do %>
   <i class="fas fa-trash-alt"></i>
	<%end%>
</div>

app/views/spots/edit.html.erb
<div class="container-nomargin">
  <h3> Edit this spot </h3>
  <%= render'form', spot: @spot %>
  <div class="up">
    <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <%end%>
</div>
</div>

app/views/spots/index.html.erb
<div class="container">
  <%= form_tag spots_path, class: "search", method: :get do %>
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a secret spot!"%>
    <%= select_tag "category", options_for_select(@categories, params[:category]), prompt: "Filter by category", class:"form-control"%>
    <%= submit_tag "Search", class: "btn btn-margintop" %>
  <% end %>


  <% @spots.each do |spot|%>
    <div class="spot_card">
        <%#= image_tag spot_image_tag(s) , class: 'spot_img' %>
      <% if spot.photos.attached? %>
        <%= link_to spot_path(spot) do%>
          <% photo = spot.photos.sample%>
          <%= cl_image_tag photo.key, class: 'spot_img' %>
        <%end%>
      <% else %>
        <%= link_to spot_path(spot) do%>
          <%= image_tag "spot.jpg", class: 'spot_img'%>
        <%end%>
      <% end %>
        <div class="spot_content">
          <%= link_to spot.name, spot_path(spot), class: 'spot_name' %>
          <p class="spot_text"><strong>Address: </strong><%= spot.address%></p>
          <p class="spot_text"><strong>Category: </strong><%= spot.category.capitalize%></p>

          <span class="spot_text">Rating:</span>
          <% avg_rating(spot).times do %>
            <i class="fas fa-camera"></i>
          <% end %>
          <% if current_user %>
            <% if current_user.moderator? %>
              <%= render "moderator_destroy", spot: spot %>
            <% end %>
          <% end %>
        </div>
        <div id="favorite">
          <%= render "favorites/add_fav", spot: spot %>
        </div>

    </div>
  <% end %>
</div>

<div class="up" id="scrollTop">
  <%#= link_to spots_path(anchor: 'menu') do %>
  <i class="fas fa-arrow-up"></i>
  <%# <% end %>
</div>

app/views/spots/new.html.erb
<div class="container-nomargin">
  <h3 class="small-title"> Create your spot! </h3>
  <%= render'form', spot: @spot %>
  <div class="up">
      <%= link_to :back do %>
      <i class="fas fa-arrow-left"></i>
    <%end%>
  </div>
</div>

app/views/spots/show.html.erb
<div class="container">
  <h1 class="small-text"> Spot information </h1>
</div>
  <div class="horizontal">
    <div class="scroll" id="pictures_list">
      <% if @pictures.count > 1 %>
        <% @pictures.each do |photo|%>
          <div class="picture_dot gallery" style="background-image: url('<%= cl_image_path photo.key %>')"> </div>
        <%#= cl_image_tag photo.key, class: 'spot_img gallery' %>
        <% end %>
      <% elsif @pictures.count === 1%>
        <% photo = @pictures.sample%>
        <%= cl_image_tag photo.key, class: 'spot_img' %>
      <% else %>
       <%= image_tag "spot.jpg", class: 'spot_img' %>
      <% end %>
    </div>
      <% if @pictures.count > 1 %>
        <div class="pagination">
          <% @pictures.count.times do%>
            <div class="dot"></div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="container-nomargin">
        <div class="spot_content">
            <% if current_user %>
              <% if current_user.moderator? %>
            <div class="mod_actions">
              <p>As a moderator you can perform this actions on this spot:</p>
                <%= render "moderator_destroy", spot: @spot %>
            </div>
              <% end %>
            <% end %>
          <% if current_user%>
            <% unless current_user.moderator?%>
            <div class="favorite">
              <%= render "favorites/add_fav", spot: @spot %>
            </div>
            <%end%>
          <%end%>
          <h3 class="spot_name spot_name-blue"><%=@spot.name%></h3>
          <p class="spot_text"><strong>Category: </strong><%= @spot.category.capitalize%></p>
          <div>
          <span>Rating:</span>
          <% avg_rating(@spot).times do %>
          <i class="fas fa-camera"></i>
          <% end %>
          </div>

            <% if current_user.blank? || !current_user.moderator? %>
              <%= link_to "https://www.google.com/maps/dir//#{@spot.address}/@#{@spot.latitude},#{@spot.longitude},z", class: 'info_action right', target: '_blank' do %>

                <i class="fas fa-directions"></i>
              <% end %>

          <%end%>
          <p class="spot_text"><strong>Address: </strong><%= @spot.address%></p>
          <br>
          <p class="spot_name-blue">Description</p>
          <p class="spot_text"> <%= @spot.description%> </p>


           <%#= link_to '< Back to list', spots_path, class: 'btn-small' %>
<br>
<h3 class="card-link">Reviews</h3>
  <% if @spot.reviews.empty? %>
    <p>Sorry... this spot has not been reviewed yet.<br>
    Be the first.</p>
  <% else %>
  <div class="horizontal" id="reviews">
        <div class="scroll">
            <% if @spot.reviews.reverse.count > 1%>
              <% @spot.reviews.reverse.each do |b|%>
                <div class="review_box" id="review_id_<%=b.id%>">
                  <% if current_user %>
                    <% unless current_user.moderator?%>
                        <%= link_to new_review_report_path(b) do %>
                        <div class="reports_btns">
                        <i class="fas fa-bullhorn"></i>
                        </div>
                        <%end%>
                    <%end%>
                  <%end%>
                  <div class="badge">
                    <% b.rating.to_i.times do %>
                  <i class="fas fa-camera"></i>
                    <% end %>
                  </div>
                  <p><strong>By
                  <%= b.user.first_name %>
                  <%= b.user.last_name %>
                  </p></strong>
                  <p class="review_descripition"><%= b.description %></p>
                  <%= render "likes/like", spot: @spot, review: b %>
                  <% if current_user %>
                    <% if current_user.moderator? %>
                      <%= render "reviews/moderator_destroy", spot: @spot, review: b %>
                    <% end %>
                  <% end %>
                </div>
              <%end%>
            <%else%>
              <% @spot.reviews.reverse.each do |b|%>
                  <div class="review_box review_box-full" id="review_id_<%=b.id%>">
                              <% if current_user %>
                    <% unless current_user.moderator?%>
                        <%= link_to new_review_report_path(b) do %>
                        <div class="reports_btns">
                        <i class="fas fa-bullhorn"></i>
                        </div>
                        <%end%>
                    <%end%>
                  <%end%>
                    <div class="badge">
                      <% b.rating.to_i.times do %>
                      <i class="fas fa-camera"></i>
                      <% end %>
                    </div>
                        <p><strong>By <%=b.user.first_name %> <%= b.user.last_name %></strong></p>
                        <p class="review_descripition"><%= b.description %></p>
                  <%= render "likes/like", spot: @spot, review: b %>
                  <% if current_user %>
                    <% if current_user.moderator? %>
                      <%= render "reviews/moderator_destroy", review: b %>
                    <% end %>
                  <% end %>
                </div>
              <%end%>
            <%end%>
        </div>
    </div>
  </div>
  <% end %>
    <%= link_to 'write a review', new_spot_review_path(@spot), class: 'btn' %>
         </div>
  </div>



  <div class="container-nomargin text-center">
    <% if current_user %>
    <% unless current_user.moderator?%>
    <br>
        <%= link_to new_spot_report_path(@spot) do %>
        <span class="btn-small">Report spot</span>
        <i class="fas fa-bullhorn"></i>
        <%end%>
      <%end%>
    <%end%>
    </div>

<%#= link_to '< Back to list', spots_path, class: 'btn-small' %>
<div class="up">
    <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <%end%>
</div>