config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get 'map', to: 'pages#map'
  resources :reports, only: %i[update]
  resources :spots do
    resources :reviews, only: %i[new create] do
      resources :likes, only: %i[create] do
        collection do
          delete :destroy
        end
      end
    end
  end
  resources :reviews, only: %i[destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots do
    resources :favorites, only: %i[create] do
      collection do
        delete :destroy
      end
    end
  end
  resources :spots, :reviews do
    resources :reports, only: %i[new create]
  end
  resources :reports, only: %i[destroy]
  get "outlaws/:id", to: "outlaws#banned", as: :outlaw
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<div id="<%= spot.id%>">
 <h1 class="spot_name spot_name-blue"><%= spot.name%></h1>
  <%#= link_to spot.name.capitalize, spot_path(spot), class: 'spot_name'%>
  <p><strong>Address: </strong><%= spot.address %></p>
  <p><strong>Category: </strong><%= spot.category %></p>

  <div class="info">
    <%= link_to spot_path(spot), class: 'info_action' do%>
      <i class="fas fa-info-circle"></i>
      <span>See more</span>
    <%end%>
    <br>
    <%= link_to "https://www.google.com/maps/dir//#{spot.address}/@#{spot.latitude},#{spot.longitude},z", class: 'info_action', target: '_blank' do %>
      <i class="fas fa-directions"></i>
      <span>Directions</span>
    <%end%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="menu">
  <div class="menu_box">
  <%= link_to spots_path,class: "menu_item #{current_class?(spots_path)}" do%>
        <%= image_tag "logo.png" , class: 'menu_icon' %>
        <p class="menu_text">Secrets</p>
        <%end%>
  </div>
  <div class="menu_box">

  <%= link_to map_path, class: "menu_item #{current_class?(map_path)}" do%>

        <%= image_tag "pin.png" , class: 'menu_icon' %>
        <p class="menu_text">Map</p>
        <%end%>
  </div>
  <div class="menu_box">
    <% if user_signed_in? %>
    <%= link_to dashboard_path ,class: "menu_item #{current_class?(dashboard_path)}" do %>
    <%= image_tag "profile.png" , class: 'menu_icon' %>
    <p class="menu_text">Profile</p>
    <%end%>
    <% else %>
    <%= link_to new_user_session_path ,class: "menu_item #{current_class?(new_user_session_path)}" do%>
    <%= image_tag "profile.png" , class: 'menu_icon' %>
    <p class="menu_text">Log in</p>
    <%end%>
    <% end %>
  </div>

</div>