config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get 'map', to: 'pages#map'
  resources :reports, only: %i[update]
  resources :spots do
    resources :reviews, only: %i[new create] do
      resources :likes, only: %i[create] do
        collection do
          delete :destroy
        end
      end
    end
  end
  resources :reviews, only: %i[destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots do
    resources :favorites, only: %i[create] do
      collection do
        delete :destroy
      end
    end
  end
  resources :spots, :reviews do
    resources :reports, only: %i[new create]
  end
  resources :reports, only: %i[destroy]
  get "outlaws/:id", to: "outlaws#banned", as: :outlaw
end

app/views/pages/_moderator.html.erb
<div class="container">
  <div class="moderator_logo">
    <%= image_tag 'police_car.svg' %>
  <p>Welcome to: <br> <span class="small-text">Secretspot Police</span></p>
  </div>
    <div class="profile_card profile_card-moderator">
    <div class="profile_content">
      <div class="profile_text">
      <p class="spot_name">Moderator</p>
      <p class="spot_text"><strong>Username: </strong><%= @user.username%></p>
      <p class="spot_text"><strong>Email: </strong><%= @user.email%></p>
      </div>
      <div class="profile_media">
        <%= user_image_tag @user, class: 'profile_pic'%>
        <%= link_to edit_user_registration_path do%>
          <%# <i class="fas fa-certificate float-right"></i> %>
          <i class="fas fa-award float-right"></i>
        <% end%>
      </div>
    </div>
  </div>

</div>


<div class="horizontal" id="upcoming">
          
  <h3 class="spot_name-blue" >Upcoming duties: tot <%= @upcoming_duty.count%></h3>
    <% if @upcoming_duty.any?%>
      <div class="scroll">
      <% @upcoming_duty.reverse.each do |d|%>
        <div class="report_box" id="report_id_<%=d.id%>">
          <p class="spot_name-blue">Report #<%=d.id%></p>
          <p class="spot_text"><strong>Intervention at: </strong>
          <% if d.reportable_type === 'Spot' %>
            <%= link_to spot_path(d.reportable_id), class: 'btn-small' do%>
              <span>Item <%=Spot.find(d.reportable_id).id%></span>
              <i class="fas fa-exclamation-triangle"></i>
            <%end%>
          <%elsif d.reportable_type === 'Review'%>
            <% rev = Review.find(d.reportable_id)%>
           <%= link_to spot_path(rev.spot, anchor: "review_id_#{rev.id}"), class: 'btn-small' do%>
              <span>Item<%=Review.find(d.reportable_id).id%></span>
              <i class="fas fa-exclamation-triangle"></i>
            <%end%>
          <%end%>
          </p>
          <p class="spot_text"><strong>Type: </strong><%= d.reportable_type%></p>
          <p class="spot_text"><strong>Category: </strong><%= d.category%></p>
          <p class="spot_text"><strong>Content Report: </strong><%= d.description%></p>
          <p class="spot_text"><strong>Filed by: </strong><%= User.find(d.user_id).first_name%> <%= d.user.last_name.capitalize%></p>
            <% if d.reportable_type === 'Spot' %>
            <p class="spot_text"><strong>Reported user: </strong> <%=  Spot.find(d.reportable_id).user.username %> </p>
            <%= link_to spot_path(d.reportable_id), class: 'btn-small' do%>
              <i class="fas fa-search-minus"></i>
            <span class="btn-small">Inspect Content</span>
            <%end%>
                <br>
           <br>
            <%= link_to outlaw_path(Spot.find(d.reportable_id).user), class: 'btn-small' do %>
              <i class="fas fa-user-slash"></i>
              <span class="btn-small">Ban User</span>
            <%end%>
          <%elsif d.reportable_type === 'Review'%>
            <% rev = Review.find(d.reportable_id)%>
            <p class="spot_text"><strong>Reported user: </strong> <%=  rev.user.username %> </p>
           <%= link_to spot_path(rev.spot, anchor: "review_id_#{rev.id}"), class: 'btn-small' do%>
           <i class="fas fa-search-minus"></i>
           <span class="btn-small">Inspect Content</span>
           <%end%>
           <br>
          
            <%= link_to outlaw_path(rev.user), class: 'btn-small' do %>
            <i class="fas fa-user-slash"></i>
            <span class="btn-small">Ban User</span>
            <%end%>
          <%end%>
          <%= render 'reports/update', report: d %>
        </div>
      <%end%>
    </div>
    <%else%>
      <% if @upcoming_duty.any?%>
        <p class="center">Ya better get to work!</p>
      <%else%>
        <p class="center">You don't have conflicts to solve, rest and enjoy the app!</p>
      <%end%>
    <%end%>

</div>


<div class="container-nomargin">
</div>

<% if @done_duty.any?%>
<div class="horizontal" id="done">
  <h3 class="spot_name-blue">Successfull interventions</h3>
    <div class="scroll">
      <% @done_duty.reverse.each do |d|%>
        <div class="report_box report_box-done" id="report_id_<%=d.id%>">
          <p class="spot_name-blue">Report #<%=d.id%></p>
          <p class="spot_text"><strong>Type: </strong><%= d.reportable_type%></p>
          <p class="spot_text"><strong>Category: </strong><%= d.category%></p>
          <p class="spot_text"><strong>Content: </strong><%= d.description%></p>
          <p class="spot_text"><strong>Filed by: </strong><%= User.find(d.user_id).first_name%> <%= d.user.last_name.capitalize%></p>
          <div class="report_actions">
          <i class="fas fa-check-circle"></i>
          </div>
        </div>
      <%end%>
  </div>
</div>
<%end%>



<div class="container-nomargin">
</div>
  <% if @banned_users.any?%>
    <div class="horizontal" id="outlaws">
      <h3 class="spot_name-blue">Filthy outlaws</h3>
        <div class="scroll">
          <% @banned_users.reverse.each do |d|%>
            <div class="report_box report_box-done" id="outlaw_id_<%=d.id%>">
              <p class="spot_name-blue">outlaw #<%=d.id%></p>
              <p class="spot_text"><strong>Username: </strong><%= d.username%></p>
              <p class="spot_text"><strong>Email: </strong><%= d.email%></p>
              <p class="spot_text"><strong>Secretspots police caught you, filthy outlaw.</strong></p>
              <div class="report_actions">
              <i class="fas fa-check-circle"></i>
              </div>
            </div>
          <%end%>
      </div>
    </div>
  <%end%> 

<div class="container-nomargin">
  <p class="center">In the meantime... would you like to share a secret?</p>
  <%= link_to 'Add new spot', new_spot_path(@spot), class: 'btn' %>
</div>


<div class="horizontal">
  <h3 class="spot_name-blue">Favourites</h3>
  <% if @favorites.reverse.any?%>
  <div class="scroll">
    <% @favorites.reverse.each do |s|%>
    <div class="dashboard_card">

          <% if s.spot.photos.attached? %>
            <%= link_to spot_path(s.spot) do%>
              <% photo = s.spot.photos.sample%>
              <%= cl_image_tag photo.key, class: 'spot_img' %>
            <% end %>
            <% else %>
            <%= link_to spot_path(s.spot) do%>
              <%= image_tag "spot.jpg", class: 'spot_img'%>
            <% end %>
          <% end %>
        <div class="spot_content">
          <%= link_to s.spot.name, spot_path(s.spot), class: 'spot_name' %>
          <p class="spot_text"><strong>Address: </strong><%= s.spot.address%></p>
          <%#= link_to "https://www.google.com/maps/place/#{s.spot.address}/@#{s.spot.latitude},#{s.spot.longitude},z", class: 'info_action right', target: '_blank' do %>
            <%# <i class="fas fa-directions"></i> %>
          <%#end%>
          <p class="spot_text"><strong>Category: </strong><%= s.spot.category.capitalize%></p>
          <div>
          <span>Rating:</span>
          <% avg_rating(s.spot).times do %>
          <i class="fas fa-camera"></i>
          <% end %>
          </div>
          <div class="actions">
          <%= link_to new_spot_review_path(s.spot) , class: 'actions_btn' do %>
          <i class="fas fa-comment-medical"></i>
          <%end%>

          </div>

        </div>
          <div id="favorite">
            <%= render "favorites/add_fav", spot: s.spot %>
          </div>
    </div>
  <% end%>
  </div>
  <%else%>
    <p class="center">You don't have any favourites, browse for secrets!</p>
    <%= link_to 'Browse', spots_path, class: 'btn' %>
  <%end%>
</div>


<div class="container-logout">
<p>Done with sharing secrets?
<%= link_to "Logout.", destroy_user_session_path, method: :delete, class: "btn-small" %></p>
</div>

app/views/pages/_visitor.html.erb
<div class="container">
  <h1 class="small-text">This is your profile, <%=@user.first_name.capitalize%>!</h1>
  <div class="profile_card">
    <div class="profile_content">
      <div class="profile_text">
      <p class="spot_name">Details:</p>
      <p class="spot_text"><strong>First Name: </strong><%= @user.first_name.capitalize%></p>
      <p class="spot_text"><strong>Last Name: </strong><%= @user.last_name.capitalize%></p>
      <p class="spot_text"><strong>Username: </strong><%= @user.username%></p>
      <p class="spot_text"><strong>Email: </strong><%= @user.email%></p>
      </div>
      <div class="profile_media">
        <%= user_image_tag @user, class: 'profile_pic'%>
          <%= link_to edit_user_registration_path do %>
          <i class="fas fa-edit float-right"></i>
        <% end%>
      </div>
    </div>
  </div>
</div>

<div class="horizontal">
  <h3 class="spot_name-blue">Your spots</h3>
  <% if @spots.any?%>
  <div class="scroll">
    <% @spots.each do |s|%>
    <div class="dashboard_card">
        <% if s.photos.attached? %>
          <%= link_to spot_path(s) do%>
          <% photo = s.photos.sample%>
          <%= cl_image_tag photo.key, class: 'spot_img' %>
          <%end%>
        <% else %>
         <%= link_to spot_path(s) do%>
          <%= image_tag "spot.jpg", class: 'spot_img'%>
          <%end%>
        <%end%>

        <div class="spot_content">


            <%= link_to s.name, spot_path(s), class: 'spot_name' %>

            <p class="spot_text"><strong>Address: </strong><%= s.address%></p>

            <p class="spot_text"><strong>Category: </strong><%= s.category.capitalize%></p>


          <div class ="icons-edit-delete-review-spot">
          <span>Rating:</span>
          <% avg_rating(s).times do %>

            <i class="fas fa-camera"></i>
          <% end %>
          </div>


          <div class="actions">
              <%= link_to edit_spot_path(s), class: 'actions_btn' do %>
              <i class="fas fa-edit"></i>
            <%end%>
          <%= link_to spot_path(s), class: 'actions_btn', method: :delete, data: {confirm: 'Do you want to delete the bench?'} do %>
            <i class="fas fa-trash-alt"></i>
          <%end%>
          </div>




        </div>


    </div>
    <% end %>
  </div>
       <%#= render "favorites/add_fav", spot: s %>

</div>

  </div>
    <br>
    <p class="center">Would you like to share your spot?</p>
    <%= link_to 'Add new spot', new_spot_path(@spot), class: 'btn' %>
  </div>

  <%else%>
    <p class="center">You don't have any spot yet, wanna add one?</p>
    <%= link_to 'Add new spot', new_spot_path(@spot), class: 'btn' %>
  <%end%>
</div>

<div class="container-nomargin" id="favorites">
</div>

<div class="horizontal">
  <h3 class="spot_name-blue">Favourites</h3>
  <% if @favorites.reverse.any?%>
  <div class="scroll">
    <% @favorites.reverse.each do |s|%>
    <div class="dashboard_card">

          <% if s.spot.photos.attached? %>
            <%= link_to spot_path(s.spot) do%>
              <% photo = s.spot.photos.sample%>
              <%= cl_image_tag photo.key, class: 'spot_img' %>
            <% end %>
            <% else %>
            <%= link_to spot_path(s.spot) do%>
              <%= image_tag "spot.jpg", class: 'spot_img'%>
            <% end %>
          <% end %>
        <div class="spot_content">
          <%= link_to s.spot.name, spot_path(s.spot), class: 'spot_name' %>
          <p class="spot_text"><strong>Address: </strong><%= s.spot.address%></p>
          <%#= link_to "https://www.google.com/maps/place/#{s.spot.address}/@#{s.spot.latitude},#{s.spot.longitude},z", class: 'info_action right', target: '_blank' do %>
            <%# <i class="fas fa-directions"></i> %>
          <%#end%>
          <p class="spot_text"><strong>Category: </strong><%= s.spot.category.capitalize%></p>
          <div>
          <span>Rating:</span>
          <% avg_rating(s.spot).times do %>
          <i class="fas fa-camera"></i>
          <% end %>
          </div>
          <div class="actions">
          <%= link_to new_spot_review_path(s.spot) , class: 'actions_btn' do %>
          <i class="fas fa-comment-medical"></i>
          <%end%>

          </div>

        </div>
          <div id="favorite">
            <%= render "favorites/add_fav", spot: s.spot %>
          </div>
    </div>
  <% end%>
  </div>
  <%else%>
    <p class="center">You don't have any favourites, browse for secrets!</p>
    <%= link_to 'Browse', spots_path, class: 'btn' %>
  <%end%>
</div>


<div class="container-logout">
<p>Done with sharing secrets?
<%= link_to "Logout.", destroy_user_session_path, method: :delete, class: "btn-small" %></p>
</div>

app/views/pages/dashboard.html.erb
<% if current_user.moderator? %>
  <%= render 'moderator'%>
<%else%>
    <%=render 'visitor' %>
<%end%>

app/views/pages/home.html.erb
<div class="header" style="background-image: url('<%= image_path "spot.jpg" %>')">
  <div class="banner">
    <h1>Secret Spots</h1>
    <p class="effect-wrapper">Find your <span class="typed"></span><span class="cursor">&nbsp;</span></p>
  </div>
  <div class="btn">
    <%= link_to 'get started', spots_path, class: 'btn-home' %>
    <span class="emoji">👈</span>
  </div>
  <div class="signup">
    <p>Are you new?
    <%= link_to 'Signup', new_user_registration_path, class: 'btn-small' %>
    </p>
  </div>
</div>

<div class="container-home">
  <div class="text">
    <p>At Secret Spots we believe tourism should be an opportunity to experience authentic places where locals feel comfortable inviting you in their extraordinary cultures.</p>
  </div>
  <div class="main">
    <div class="single">
      <%= image_tag "undraw_adventure.png" %>
      <p>Look for authentic places and find your way to them.</p>
    </div>
    <div class="single">
      <%= image_tag "undraw_review.png" %>
      <p>Review the places you discovered through us and interact with other travelers.</p>
    </div>
    <div class="single">
      <%= image_tag "undraw_share.png" %>
      <p>Share your secrets with the rest of the world.</p>
    </div>
  </div>
</div>

app/views/pages/map.html.erb
<div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>