config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  get 'map', to: 'pages#map'
  resources :reports, only: %i[update]
  resources :spots do
    resources :reviews, only: %i[new create] do
      resources :likes, only: %i[create] do
        collection do
          delete :destroy
        end
      end
    end
  end
  resources :reviews, only: %i[destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots do
    resources :favorites, only: %i[create] do
      collection do
        delete :destroy
      end
    end
  end
  resources :spots, :reviews do
    resources :reports, only: %i[new create]
  end
  resources :reports, only: %i[destroy]
  get "outlaws/:id", to: "outlaws#banned", as: :outlaw
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :reportable, polymorphic: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[update]
  # before_action :set_spot, only: %i[create]
  def update
    @report.done = true
    @report.save
    flash.now[:alert] = "Thank you for accomplishing the mission so diligently!
    Secretspots society is eternally grateful to you."
    redirect_to dashboard_path(anchor: :done)
  end

   def create
      @parent = parent
      @report = Report.new(report_params)
      @report.reportable = @parent
      if @report.save
        redirect_to dashboard_path

      else
        render "new"
      end
   end

   def new
      @parent = parent
      @report = Report.new
   end

   private

   def parent
      if params[:spot_id]
        Spot.find params[:spot_id]
      else
        Review.find params[:review_id]
      end
   end

   def report_params
      params.require(:report).permit(:description, :category).merge(user_id: current_user.id)
   end
   
   def set_report
     @report = Report.find(params[:id])
   end

   def set_spot
    @spot = Spot.find(params[:spot_id])
   end
 end

app/views/reports/_form.html.erb
<p class="text-center"> Report this to the moderators and help us keeping the website safe!</p>

<h3 class="small-title">Reporting item: <%=@parent.class%> #<%=@parent.id%></h3>
  <%= simple_form_for [@parent, @report]  do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :category, as: :select, collection: ["Spam", "Inappropriate"] %>
    <%= f.input :description%>
    <%= f.submit class: 'btn'%>
  <% end %>

app/views/reports/_update.html.erb
<div class="actions">
  <%= link_to report_path(report), method: :patch do %>
  <span class="btn-small"><i class="far fa-check-circle"></i></span>
  <span class="btn-small">Mark Done</span>
  <%end%>
</div>

app/views/reports/new.html.erb
<div class="container">
  <%= render'form', report: @report %>
  <div class="up">
      <%= link_to :back do %>
      <i class="fas fa-arrow-left"></i>
    <%end%>
  </div>
</div>

<div class="up">
    <%= link_to :back do %>
    <i class="fas fa-arrow-left"></i>
  <%end%>
</div>